import type { IClient } from "./types";

export const clientsMock: IClient[] = [
  {
    id: 1,
    name: "Алина Ержанова",
    image: "/images/client.jpg",
    age: 7,
    rate: "INDIVIDUAL",
    parent: "Ержанов Руслан",
    parent_number: "+7 707 123 45 67",
    status: "ACTIVE",
    driver: "Айдар Бекенов",
  },
  {
    id: 2,
    name: "Михаил Сапаров",
    image: "/images/client.jpg",
    age: 9,
    rate: "GROUP",
    parent: "Сапарова Анна",
    parent_number: "+7 701 765 43 21",
    status: "NEW",
    driver: "Серик Каримов",
  },
  {
    id: 3,
    name: "Жания Тулебаева",
    image: "/images/client.jpg",
    age: 8,
    rate: "INDIVIDUAL",
    parent: "Тулебаева Гульмира",
    parent_number: "+7 702 555 88 44",
    status: "STOPPED",
    driver: "Айдар Бекенов",
  },
  {
    id: 4,
    name: "Ильяс Кенжебек",
    image: "/images/client.jpg",
    age: 6,
    rate: "GROUP",
    parent: "Кенжебек Айгуль",
    parent_number: "+7 705 999 11 22",
    status: "ACTIVE",
    driver: "Бахтияр Аманов",
  },
  {
    id: 5,
    name: "Аяулым Рамазанова",
    image: "/images/client.jpg",
    age: 10,
    rate: "GROUP",
    parent: "Рамазанов Ермек",
    parent_number: "+7 708 432 10 98",
    status: "NEW",
    driver: "Серик Каримов",
  },
];
